name: Deploy via ftp
on:
  push:
    branches:
     - master
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Upload ftp
      uses: genietim/ftp-action@master
      with:
        host: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: "/github/workspace/"
        remoteDir: "/
